-- AlterTable
ALTER TABLE "Device" ADD COLUMN     "activationDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "batteryPercentage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lastActiveDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "lastRuntime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
